#pragma once

// This file defines what appears on the Main Page of the documentation
// generated by doxygen. The file contains no code, and does not appear
// in any cpp include statement.
//
/*!
 * \mainpage MPAS-JEDI Interface
 *
 * MPAS-JEDI is the interface between the generic components of the JEDI system and the atmospheric core of the
 * Model for Prediction Across Scales (MPAS). The primary development partners for MPAS are Los Alamos National
 * Laboratory (LANL) and the National Center for Atmospheric Research (NCAR).
 */
